
# Medin Zukanovic

import tkinter as tk
from PIL import ImageTk,Image

root= tk.Tk()
root.title("SPOI")
pocetna=tk.Label(root, text="Dobrodošli")
pocetna.pack()
pocetna1=tk.Label(root, text="Odaberite broj gradova")
pocetna1.pack()
r=tk.IntVar()
w1=tk.Radiobutton(root,text="3",variable=r,value=3).pack()
w2=tk.Radiobutton(root,text="4",variable=r,value=4).pack()
w3=tk.Radiobutton(root,text="5",variable=r,value=5).pack()
def noviprozor1():
    top1 = tk.Toplevel()
    tk.Label(top1, text="Odaberi polazni grad:").pack()
    d=tk.IntVar()
    d1=tk.Radiobutton(top1,text="1",variable=r,value=1).pack()
    d2=tk.Radiobutton(top1,text="2",variable=r,value=2).pack()
    d3=tk.Radiobutton(top1,text="3",variable=r,value=3).pack()   
    d4=tk.Radiobutton(top1,text="4",variable=r,value=4).pack() 
    d5=tk.Radiobutton(top1,text="4",variable=r,value=5).pack()
    d6=tk.Radiobutton(top1,text="4",variable=r,value=6).pack()
    d7=tk.Radiobutton(top1,text="4",variable=r,value=7).pack()
    d8=tk.Radiobutton(top1,text="4",variable=r,value=8).pack()
    d9=tk.Radiobutton(top1,text="4",variable=r,value=9).pack()
    d10=tk.Radiobutton(top1,text="4",variable=r,value=10).pack()
    d11=tk.Radiobutton(top1,text="4",variable=r,value=11).pack()
    d12=tk.Radiobutton(top1,text="4",variable=r,value=12).pack()
    d13=tk.Radiobutton(top1,text="4",variable=r,value=13).pack()
    d14=tk.Radiobutton(top1,text="4",variable=r,value=14).pack()
    d15=tk.Radiobutton(top1,text="4",variable=r,value=15).pack()
    d16=tk.Radiobutton(top1,text="4",variable=r,value=16).pack()
    d17=tk.Radiobutton(top1,text="4",variable=r,value=17).pack()
    d18=tk.Radiobutton(top1,text="4",variable=r,value=18).pack()
    d19=tk.Radiobutton(top1,text="4",variable=r,value=19).pack()
    d20=tk.Radiobutton(top1,text="4",variable=r,value=20).pack()

    button2= tk.Button(top1,text="Potvdi",command=noviprozor)
    button2.pack()

    button1.pack()

def noviprozor():
    top = tk.Toplevel()
    tk.Label(top, text="Odaberi gradove:").pack()
    var1 = tk.IntVar()
    tk.Checkbutton(top, text="100", variable=var1).pack()
    var2 = tk.IntVar()
    tk.Checkbutton(top, text="2", variable=var2).pack()
    var3 = tk.IntVar()
    tk.Checkbutton(top, text="3", variable=var3).pack()
    var4 = tk.IntVar()
    tk.Checkbutton(top, text="4", variable=var4).pack()
    var5 = tk.IntVar()
    tk.Checkbutton(top, text="5", variable=var5).pack()
    var6 = tk.IntVar()
    tk.Checkbutton(top, text="6", variable=var6).pack()
    var7 = tk.IntVar()
    tk.Checkbutton(top, text="7", variable=var7).pack()
    var8 = tk.IntVar()
    tk.Checkbutton(top, text="8", variable=var8).pack()
    var9 = tk.IntVar()
    tk.Checkbutton(top, text="9", variable=var9).pack()
    var10 = tk.IntVar()
    tk.Checkbutton(top, text="10", variable=var10).pack()
    var11 = tk.IntVar()
    tk.Checkbutton(top, text="11", variable=var11).pack()
    var12 = tk.IntVar()
    tk.Checkbutton(top, text="12", variable=var12).pack()
    var13 = tk.IntVar()
    tk.Checkbutton(top, text="13", variable=var13).pack()
    var14 = tk.IntVar()
    tk.Checkbutton(top, text="14", variable=var14).pack()
    var15 = tk.IntVar()
    tk.Checkbutton(top, text="15", variable=var15).pack()
    var16 = tk.IntVar()
    tk.Checkbutton(top, text="16", variable=var16).pack()
    var17 = tk.IntVar()
    tk.Checkbutton(top, text="17", variable=var17).pack()
    var18 = tk.IntVar()
    tk.Checkbutton(top, text="18", variable=var18).pack()
    var19 = tk.IntVar()
    tk.Checkbutton(top, text="19", variable=var19).pack()
    var20 = tk.IntVar()
    tk.Checkbutton(top, text="20", variable=var20).pack()
    
button1= tk.Button(root,text="Potvdi",command=noviprozor1)
button1.pack()

root.mainloop()

